Engine RPM: Engine Speed (rpm)
Gear: Gear (gear)
Wheel Speed: Slowest Wheel (km/h)
Multiplier 1: 123.49
Multiplier 2: 75.70
Multiplier 3: 48.21
Multiplier 4: 32.99
Multiplier 5: 24.53
Multiplier 6: 19.45